"""
Autogenerated Skill Models

Tracks skills that were auto-generated by the system.
"""
from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import Column, String, DateTime, Integer, Float, Text, Boolean
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

from database import Base


class AutogeneratedSkill(Base):
    """
    Autogenerated skill with tracking.

    Lifecycle:
    experimental → (after good metrics) → stable
    experimental → (after 30 days unused) → deprecated
    """
    __tablename__ = "autogenerated_skills"

    # Primary key
    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)

    # Identification
    skill_id = Column(String(255), unique=True, nullable=False)
    version = Column(String(50), nullable=False)

    # Generation metadata
    generation_trigger = Column(String(100))  # missing_capability, failure_rate
    llm_model = Column(String(100))
    generation_prompt_tokens = Column(Integer)

    # Validation
    validation_status = Column(String(50))  # pending, passed, failed
    validation_errors = Column(Text)

    # Status lifecycle
    status = Column(String(50), nullable=False)  # experimental, stable, deprecated

    # Performance
    total_executions = Column(Integer, default=0)
    success_rate = Column(Float)
    avg_latency_ms = Column(Float)

    # Improvement tracking
    parent_skill_id = Column(String(255))  # If this is improved version
    improvement_version = Column(Integer, default=0)

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    first_used_at = Column(DateTime(timezone=True))
    last_used_at = Column(DateTime(timezone=True))
    promoted_to_stable_at = Column(DateTime(timezone=True))

    def to_dict(self):
        return {
            "skill_id": self.skill_id,
            "version": self.version,
            "status": self.status,
            "total_executions": self.total_executions,
            "success_rate": self.success_rate,
            "generation_trigger": self.generation_trigger
        }
