"""
MCP (Modular Capability Plugin) Skill System for AI-OS
======================================================

This module provides MCP-based skill management with:
- Dynamic skill loading/unloading
- Sandbox execution
- Auto-generation with validation
- Skill improvement loop

Architecture:
    GoalExecutor → MCP → Skill Plugins
                         ↓
                    Autogenerate
                         ↓
                    Validate (sandbox)
                         ↓
                    Register
"""

import os
import re
import json
import importlib
import importlib.util
from pathlib import Path
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass, field
from enum import Enum
import logging

logger = logging.getLogger(__name__)


class SkillStatus(Enum):
    """Skill lifecycle status."""
    EXPERIMENTAL = "experimental"
    VALIDATED = "validated"
    ACTIVE = "active"
    DISABLED = "disabled"
    FAILED = "failed"


@dataclass
class SkillPlugin:
    """MCP Skill Plugin representation."""
    id: str
    name: str
    version: str
    capabilities: List[str]
    requirements: List[str]
    input_schema: Dict
    output_schema: Dict
    produces_artifacts: List[str]
    execute_fn: Optional[Callable] = None
    status: SkillStatus = SkillStatus.EXPERIMENTAL
    source: str = "manual"  # "manual", "autogenerated", "mcp"
    execution_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    metadata: Dict = field(default_factory=dict)
    
    @property
    def success_rate(self) -> float:
        if self.execution_count == 0:
            return 0.0
        return self.success_count / self.execution_count


@dataclass
class ExecutionResult:
    """Result of skill execution."""
    success: bool
    output: Dict
    artifacts: List[Dict]
    error: Optional[str] = None
    duration_ms: int = 0
    skill_id: str = ""


class MCPSkillSystem:
    """
    Modular Capability Plugin System for AI-OS.
    
    Manages skills as plugins with:
    - Dynamic loading
    - Sandbox execution
    - Auto-generation
    - Versioning
    - Metrics
    """
    
    def __init__(self):
        self.plugins: Dict[str, SkillPlugin] = {}
        self.autogenerated_dir = Path("/app/canonical_skills/autogenerated")
        self.mcp_plugins_dir = Path("/app/canonical_skills/mcp")
        
        # Create directories
        self.autogenerated_dir.mkdir(exist_ok=True)
        self.mcp_plugins_dir.mkdir(exist_ok=True)
        
        # Load built-in skills
        self._load_builtin_skills()
        
    def _load_builtin_skills(self):
        """Load built-in skills from canonical_skills."""
        from canonical_skills.registry import skill_registry
        
        for skill in skill_registry.list():
            plugin = SkillPlugin(
                id=getattr(skill, 'id', skill.__class__.__name__.lower()),
                name=skill.__class__.__name__,
                version=getattr(skill, 'version', '1.0'),
                capabilities=getattr(skill, 'capabilities', []),
                requirements=getattr(skill, 'requirements', []),
                input_schema=getattr(skill, 'input_schema', {}),
                output_schema=getattr(skill, 'output_schema', {}),
                produces_artifacts=getattr(skill, 'produces_artifacts', []),
                status=SkillStatus.ACTIVE,
                source="manual"
            )
            self.plugins[plugin.id] = plugin
            
        logger.info("mcp_skills_loaded", count=len(self.plugins))
    
    # =========================================================================
    # Skill Execution
    # =========================================================================
    
    async def execute_skill(
        self,
        skill_id: str,
        input_data: Dict,
        context: Dict
    ) -> ExecutionResult:
        """Execute a skill with sandboxing."""
        import time
        start = time.time()
        
        if skill_id not in self.plugins:
            return ExecutionResult(
                success=False,
                output={},
                artifacts=[],
                error=f"Skill {skill_id} not found",
                skill_id=skill_id
            )
        
        plugin = self.plugins[skill_id]
        
        # Check if skill is active
        if plugin.status not in [SkillStatus.ACTIVE, SkillStatus.VALIDATED]:
            return ExecutionResult(
                success=False,
                output={},
                artifacts=[],
                error=f"Skill {skill_id} is {plugin.status.value}",
                skill_id=skill_id
            )
        
        try:
            # Execute skill
            if plugin.execute_fn:
                result = plugin.execute_fn(input_data, context)
            else:
                # Try to load and execute
                result = self._execute_plugin(plugin, input_data, context)
            
            # Update metrics
            plugin.execution_count += 1
            if result.success:
                plugin.success_count += 1
            
            duration = int((time.time() - start) * 1000)
            result.duration_ms = duration
            result.skill_id = skill_id
            
            logger.info(
                "mcp_skill_executed",
                skill_id=skill_id,
                success=result.success,
                duration_ms=duration
            )
            
            return result
            
        except Exception as e:
            plugin.execution_count += 1
            plugin.failure_count += 1
            
            duration = int((time.time() - start) * 1000)
            
            logger.error(
                "mcp_skill_error",
                skill_id=skill_id,
                error=str(e)
            )
            
            return ExecutionResult(
                success=False,
                output={},
                artifacts=[],
                error=str(e),
                duration_ms=duration,
                skill_id=skill_id
            )
    
    def _execute_plugin(self, plugin: SkillPlugin, input_data: Dict, context: Dict) -> ExecutionResult:
        """Execute a plugin by loading its module."""
        # For now, delegate to canonical_skills
        from canonical_skills.registry import skill_registry
        
        skill = skill_registry.get(plugin.id)
        if not skill:
            return ExecutionResult(
                success=False,
                output={},
                artifacts=[],
                error=f"Skill {plugin.id} not found in registry"
            )
        
        result = skill.execute(input_data, context)
        
        return ExecutionResult(
            success=result.success,
            output=result.output,
            artifacts=[a.to_dict() for a in result.artifacts],
            error=result.error
        )
    
    # =========================================================================
    # Skill Discovery
    # =========================================================================
    
    def find_skill_for_goal(self, goal_title: str, goal_type: str = "achievable") -> Optional[str]:
        """Find appropriate skill for a goal."""
        required_caps = self._extract_capabilities(goal_title)
        
        if not required_caps:
            return None
        
        # Find best matching skill
        best_match = None
        best_score = 0
        
        for skill_id, plugin in self.plugins.items():
            if plugin.status not in [SkillStatus.ACTIVE, SkillStatus.VALIDATED]:
                continue
            
            score = self._calculate_match_score(plugin, required_caps)
            if score > best_score:
                best_score = score
                best_match = skill_id
        
        return best_match
    
    def find_missing_capabilities(self, goal_title: str) -> List[str]:
        """Find capabilities that don't have a skill."""
        required_caps = self._extract_capabilities(goal_title)
        
        existing_caps = set()
        for plugin in self.plugins.values():
            if plugin.status in [SkillStatus.ACTIVE, SkillStatus.VALIDATED]:
                existing_caps.update(plugin.capabilities)
        
        return [cap for cap in required_caps if cap not in existing_caps]
    
    def _extract_capabilities(self, text: str) -> List[str]:
        """Extract capabilities from goal text."""
        text_lower = text.lower()
        capabilities = []
        
        capability_map = {
            "search": "search", "find": "search",
            "research": "research",
            "analyze": "analyze", "analysis": "analyze",
            "extract": "extract",
            "summarize": "summarize", "summary": "summarize",
            "write": "file-write", "create": "file-write",
            "read": "file-read",
            "list": "file-list",
            "run": "execute", "command": "execute",
            "api": "api-call", "http": "api-call",
            "database": "database", "sql": "database",
            "test": "testing",
            "convert": "convert", "transform": "convert",
            "email": "communication", "send": "communication",
        }
        
        for keyword, capability in capability_map.items():
            if keyword in text_lower and capability not in capabilities:
                capabilities.append(capability)
        
        return capabilities
    
    def _calculate_match_score(self, plugin: SkillPlugin, required: List[str]) -> int:
        """Calculate how well a skill matches required capabilities."""
        score = 0
        for cap in required:
            if cap in plugin.capabilities:
                score += 10
        
        # Bonus for validated/active status
        if plugin.status == SkillStatus.ACTIVE:
            score += 5
        elif plugin.status == SkillStatus.VALIDATED:
            score += 2
        
        # Bonus for proven success rate
        if plugin.execution_count > 5:
            score += int(plugin.success_rate * 5)
        
        return score
    
    # =========================================================================
    # Auto-generation
    # =========================================================================
    
    def generate_skill(self, capability: str) -> Optional[SkillPlugin]:
        """Auto-generate a skill for a missing capability."""
        skill_id = f"mcp.{capability}"
        
        if skill_id in self.plugins:
            logger.info("skill_already_exists", skill_id=skill_id)
            return self.plugins[skill_id]
        
        # Generate code
        code = self._generate_skill_code(skill_id, capability)
        
        # Save to file
        filename = f"{skill_id.replace('.', '_')}.py"
        filepath = self.autogenerated_dir / filename
        
        with open(filepath, 'w') as f:
            f.write(code)
        
        # Create plugin
        plugin = SkillPlugin(
            id=skill_id,
            name=f"MCPCapability{capability.title().replace('-', '')}Skill",
            version="0.1.0",
            capabilities=[capability],
            requirements=[],
            input_schema={"type": "object", "properties": {"data": {"type": "string"}}},
            output_schema={"type": "object"},
            produces_artifacts=["KNOWLEDGE"],
            status=SkillStatus.EXPERIMENTAL,
            source="autogenerated"
        )
        
        self.plugins[skill_id] = plugin
        
        logger.info("skill_autogenerated", skill_id=skill_id, capability=capability)
        
        return plugin
    
    def _generate_skill_code(self, skill_id: str, capability: str) -> str:
        """Generate skill code."""
        name = f"MCPCapability{capability.title().replace('-', '')}Skill"
        
        return f'''"""
MCP Auto-generated Skill: {capability}
Generated by AI-OS MCP Skill System
"""
from canonical_skills.base import Skill, SkillResult, Artifact


class {name}(Skill):
    """Auto-generated skill for {capability} capability."""
    
    id = "{skill_id}"
    version = "0.1.0"
    description = "MCP auto-generated skill for {capability}"
    
    capabilities = ["{capability}"]
    requirements = []
    
    input_schema = {{
        "type": "object",
        "properties": {{
            "data": {{"type": "string", "description": "Input data"}}
        }},
        "required": ["data"]
    }}
    
    output_schema = {{
        "type": "object",
        "properties": {{
            "result": {{"type": "string"}}
        }}
    }}
    
    produces_artifacts = ["KNOWLEDGE"]
    
    def execute(self, input_data: dict, context: dict) -> SkillResult:
        data = input_data.get("data", "")
        
        result_text = f"MCP processed: {{data[:100]}} with {capability}"
        
        artifact = self._artifact(
            type_="KNOWLEDGE",
            content=result_text,
            metadata={{"source": "{name}", "capability": "{capability}"}}
        )
        
        return self._success_result({{"result": result_text}}, [artifact])
    
    def verify(self, result: SkillResult) -> bool:
        return result.success and len(result.artifacts) > 0
'''
    
    # =========================================================================
    # Validation
    # =========================================================================
    
    def validate_skill(self, skill_id: str) -> bool:
        """Validate an autogenerated skill."""
        if skill_id not in self.plugins:
            return False
        
        plugin = self.plugins[skill_id]
        
        # Syntax check
        try:
            filepath = self.autogenerated_dir / f"{skill_id.replace('.', '_')}.py"
            if filepath.exists():
                with open(filepath) as f:
                    compile(f.read(), str(filepath), 'exec')
        except SyntaxError:
            plugin.status = SkillStatus.FAILED
            return False
        
        # Safety check
        if self._contains_dangerous_code(filepath):
            plugin.status = SkillStatus.FAILED
            return False
        
        # Test execution
        test_result = self._test_skill(skill_id)
        if test_result:
            plugin.status = SkillStatus.VALIDATED
        else:
            plugin.status = SkillStatus.FAILED
        
        return test_result
    
    def _contains_dangerous_code(self, filepath: Path) -> bool:
        """Check for dangerous operations."""
        dangerous = [
            r'rm\s+-rf',
            r'format\s+',
            r'shutil\.rmtree',
            r'exec\s*\(',
            r'eval\s*\(',
            r'subprocess.*shell=True',
        ]
        
        try:
            with open(filepath) as f:
                content = f.read()
                for pattern in dangerous:
                    if re.search(pattern, content):
                        return True
        except:
            pass
        
        return False
    
    def _test_skill(self, skill_id: str) -> bool:
        """Test skill with mock data."""
        try:
            # Run sync test - just check if module loads
            filepath = self.autogenerated_dir / f"{skill_id.replace('.', '_')}.py"
            if not filepath.exists():
                return False
            
            # Try to import and instantiate
            import sys
            module_name = skill_id.replace('.', '_')
            spec = importlib.util.spec_from_file_location(module_name, filepath)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)
                
                # Find skill class
                for attr_name in dir(module):
                    if attr_name.endswith("Skill"):
                        cls = getattr(module, attr_name)
                        if hasattr(cls, 'execute'):
                            # Try to instantiate and run
                            skill = cls()
                            result = skill.execute({"data": "test"}, {"goal_id": "test"})
                            return result.success
            
            return False
        except Exception as e:
            logger.warning("skill_test_failed", skill_id=skill_id, error=str(e))
            return False
    
    # =========================================================================
    # Skill Management
    # =========================================================================
    
    def enable_skill(self, skill_id: str) -> bool:
        """Enable a validated skill."""
        if skill_id not in self.plugins:
            return False
        
        plugin = self.plugins[skill_id]
        if plugin.status != SkillStatus.VALIDATED:
            return False
        
        plugin.status = SkillStatus.ACTIVE
        logger.info("skill_enabled", skill_id=skill_id)
        return True
    
    def disable_skill(self, skill_id: str) -> bool:
        """Disable a skill."""
        if skill_id not in self.plugins:
            return False
        
        plugin = self.plugins[skill_id]
        plugin.status = SkillStatus.DISABLED
        logger.info("skill_disabled", skill_id=skill_id)
        return True
    
    def get_skill_metrics(self, skill_id: str) -> Optional[Dict]:
        """Get skill performance metrics."""
        if skill_id not in self.plugins:
            return None
        
        plugin = self.plugins[skill_id]
        return {
            "id": plugin.id,
            "version": plugin.version,
            "status": plugin.status.value,
            "execution_count": plugin.execution_count,
            "success_count": plugin.success_count,
            "failure_count": plugin.failure_count,
            "success_rate": plugin.success_rate,
            "source": plugin.source
        }
    
    def list_skills(self, status: Optional[SkillStatus] = None) -> List[SkillPlugin]:
        """List all skills, optionally filtered by status."""
        if status:
            return [p for p in self.plugins.values() if p.status == status]
        return list(self.plugins.values())
    
    # =========================================================================
    # Improvement
    # =========================================================================
    
    def improve_skill(self, skill_id: str, feedback: Dict) -> bool:
        """Improve skill based on feedback."""
        if skill_id not in self.plugins:
            return False
        
        plugin = self.plugins[skill_id]
        
        # Increment version
        parts = plugin.version.split('.')
        parts[-1] = str(int(parts[-1]) + 1)
        plugin.version = '.'.join(parts)
        
        logger.info(
            "skill_improved",
            skill_id=skill_id,
            new_version=plugin.version,
            feedback=feedback
        )
        
        return True


# Global MCP instance
_mcp_system = None


def get_mcp_system() -> MCPSkillSystem:
    """Get global MCP skill system instance."""
    global _mcp_system
    if _mcp_system is None:
        _mcp_system = MCPSkillSystem()
    return _mcp_system


# Convenience functions
async def execute_skill(skill_id: str, input_data: Dict, context: Dict) -> ExecutionResult:
    """Execute skill via MCP."""
    mcp = get_mcp_system()
    return await mcp.execute_skill(skill_id, input_data, context)


def find_skill_for_goal(goal_title: str, goal_type: str = "achievable") -> Optional[str]:
    """Find skill for goal via MCP."""
    mcp = get_mcp_system()
    return mcp.find_skill_for_goal(goal_title, goal_type)


def auto_generate_and_register(capability: str) -> Optional[str]:
    """Auto-generate and register a skill for capability."""
    mcp = get_mcp_system()
    
    # Generate
    plugin = mcp.generate_skill(capability)
    if not plugin:
        return None
    
    # Validate
    if not mcp.validate_skill(plugin.id):
        return None
    
    # Enable
    mcp.enable_skill(plugin.id)
    
    return plugin.id
