"""
MCP Skill Generator - LLM-based skill generation through MCP gateway

Architecture:
Goal Executor → MCP Manager → Skill Generator → Validate → Register → Execute

This makes skill autogeneration:
- Modular: Skills are isolated plugins
- Safe: Sandbox validation before registration
- Extensible: Easy to add/upgrade skills without touching core
- Observable: All generations tracked via MCP
"""
import os
import asyncio
import re
from typing import List, Dict, Any, Optional
from pathlib import Path
from datetime import datetime
import importlib.util

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from database import AsyncSessionLocal
from llm_fallback import chat_with_fallback
from logging_config import get_logger
from autogenerated_skill_models import AutogeneratedSkill
from mcp_dependency_manager import mcp_dependency_manager

logger = get_logger(__name__)


class MCPSkillPlugin:
    """
    Represents an MCP skill plugin.

    Skills are isolated plugins managed by MCP, not direct code in canonical_skills.
    """

    def __init__(
        self,
        plugin_id: str,
        skill_code: str,
        capabilities: List[str],
        version: str = "0.1.0",
        status: str = "experimental"
    ):
        self.plugin_id = plugin_id
        self.skill_code = skill_code
        self.capabilities = capabilities
        self.version = version
        self.status = status  # experimental, stable, deprecated
        self.created_at = datetime.utcnow()
        self.execution_count = 0
        self.success_count = 0

        # Background generation tracking
        self.generation_status = "generating"  # generating, completed, failed
        self.generation_started_at = datetime.utcnow()
        self.generation_completed_at = None
        self.generation_error = None

    def get_skill_class(self):
        """Dynamically load skill class from code."""
        # Create temp module
        spec = importlib.util.spec_from_loader(
            f"mcp_plugin_{self.plugin_id}",
            loader=None
        )
        module = importlib.util.module_from_spec(spec)

        # Execute code in module namespace
        exec(self.skill_code, module.__dict__)

        # Find Skill class
        for attr_name in dir(module):
            attr = getattr(module, attr_name)
            # Check if it's a class and inherits from Skill (but isn't Skill itself)
            if isinstance(attr, type) and attr.__name__.endswith('Skill'):
                return attr

        raise ValueError(f"No Skill class found in plugin {self.plugin_id}")

    @property
    def success_rate(self) -> float:
        """Calculate success rate from execution history."""
        if self.execution_count == 0:
            return 0.0
        return self.success_count / self.execution_count


class MCPSkillGenerator:
    """
    Generates new skill plugins via LLM when missing capabilities detected.

    Flow:
    1. Goal executor requests skill for capabilities
    2. MCP checks if plugin exists
    3. If not, triggers generation
    4. LLM generates skill code
    5. Sandbox validation
    6. Register in MCP registry
    7. Return to goal executor
    """

    # Configuration
    MCP_PLUGINS_DIR = Path("/app/mcp_plugins")
    MAX_PLUGINS = 50
    GENERATION_MODEL = "local-coder"  # Uses Ollama qwen2.5-coder

    # Rate limiting
    MAX_CONCURRENT_GENERATIONS = 3  # Max simultaneous generations
    GENERATION_COOLDOWN_SECONDS = 60  # Min time between generations

    # Pruning settings
    PRUNING_THRESHOLD_DAYS = 30  # Prune unused skills after 30 days
    MIN_SUCCESS_RATE_FOR_RETENTION = 0.3  # Keep if >30% success
    MIN_EXECUTIONS_BEFORE_PRUNING = 5  # Only prune after 5+ executions

    def __init__(self):
        self.plugins_dir = self.MCP_PLUGINS_DIR
        self.plugins_dir.mkdir(exist_ok=True)
        self._registry: Dict[str, MCPSkillPlugin] = {}
        self._active_generations = set()  # Track concurrent generations
        self._last_generation_time = None

    async def generate_skill(
        self,
        missing_capabilities: List[str],
        requirements: Dict[str, Any],
        goal_context: Optional[Dict] = None
    ) -> str:
        """
        Generate new skill plugin for missing capabilities.

        Args:
            missing_capabilities: List of required capabilities
            requirements: Goal requirements (input_type, output_type, artifacts)
            goal_context: Optional goal context for better generation

        Returns:
            plugin_id of generated skill

        Raises:
            Exception: If generation fails or validation fails
        """
        # Step 0: Check rate limiting
        await self._check_rate_limit()

        # Mark generation as active
        temp_plugin_id = f"generating_{id(self)}"
        self._active_generations.add(temp_plugin_id)

        try:
            # Step 1: Check cap
            await self._check_plugin_cap()

            # Step 2: Build generation prompt with goal context
            prompt = self._build_generation_prompt(
                missing_capabilities,
                requirements,
                goal_context
            )

            # Step 3: Generate code via LLM
            logger.info(
                "mcp_skill_generation_started",
                capabilities=missing_capabilities,
                goal_context=goal_context,
                active_count=len(self._active_generations)
            )

            skill_code = await self._llm_generate(prompt)

            # Step 4: Extract skill class
            clean_code = self._extract_skill_class(skill_code)
            plugin_id = self._extract_plugin_id(clean_code)

            if not plugin_id:
                raise Exception("Could not extract plugin_id from generated code")

            # Update active generation tracking
            self._active_generations.discard(temp_plugin_id)
            self._active_generations.add(plugin_id)
            self._last_generation_time = datetime.utcnow()

            # Step 5: Save plugin code
            plugin_path = self.plugins_dir / f"{plugin_id}.py"
            with open(plugin_path, 'w') as f:
                f.write(clean_code)

            logger.info(
                "mcp_plugin_saved",
                plugin_id=plugin_id,
                path=str(plugin_path)
            )

            # Step 5.5: Install dependencies
            logger.info(
                "mcp_installing_dependencies",
                plugin_id=plugin_id
            )

            dep_result = await mcp_dependency_manager.install_dependencies(
                skill_code=clean_code,
                skill_id=plugin_id
            )

            if dep_result['failed']:
                logger.warning(
                    "mcp_deps_install_partial_failure",
                    plugin_id=plugin_id,
                    installed=dep_result['installed'],
                    failed=dep_result['failed']
                )

            # Step 6: Sandbox validation
            validation_result = await self._sandbox_validate(plugin_path, plugin_id)

            # Step 7: Create plugin object
            plugin = MCPSkillPlugin(
                plugin_id=plugin_id,
                skill_code=clean_code,
                capabilities=missing_capabilities,
                version="0.1.0",
                status="experimental" if validation_result["passed"] else "failed"
            )

            # Step 8: Register in MCP
            self._registry[plugin_id] = plugin

            # Step 9: Save to database
            await self._save_to_database(plugin, validation_result)

            # Update generation status
            plugin.generation_status = "completed" if validation_result["passed"] else "failed"
            plugin.generation_completed_at = datetime.utcnow()
            if not validation_result["passed"]:
                plugin.generation_error = validation_result.get("errors")

            logger.info(
                "mcp_plugin_registered",
                plugin_id=plugin_id,
                status=plugin.status,
                validation_passed=validation_result["passed"],
                generation_duration_s=(plugin.generation_completed_at - plugin.generation_started_at).total_seconds()
            )

            if not validation_result["passed"]:
                raise Exception(f"Plugin validation failed: {validation_result.get('errors')}")

            return plugin_id

        finally:
            # Always remove from active generations
            self._active_generations.discard(temp_plugin_id)
            # Also remove the actual plugin_id if it was added
            if 'plugin_id' in locals() and plugin_id in self._active_generations:
                self._active_generations.discard(plugin_id)

    async def get_plugin(self, plugin_id: str) -> Optional[MCPSkillPlugin]:
        """Get plugin by ID from MCP registry."""
        return self._registry.get(plugin_id)

    async def find_plugin_for_capabilities(
        self,
        capabilities: List[str]
    ) -> Optional[MCPSkillPlugin]:
        """
        Find best plugin for required capabilities.

        Args:
            capabilities: List of required capabilities

        Returns:
            Best matching plugin or None
        """
        if not capabilities:
            return None

        candidates = []

        for plugin_id, plugin in self._registry.items():
            if plugin.status == "deprecated":
                continue

            # Calculate match score
            matched = sum(1 for cap in capabilities if cap in plugin.capabilities)
            if matched > 0:
                # Consider success rate too
                score = matched * 10 + (plugin.success_rate * 5)
                candidates.append((score, plugin))

        if not candidates:
            return None

        # Return best match
        candidates.sort(key=lambda x: x[0], reverse=True)
        return candidates[0][1]

    async def execute_plugin(
        self,
        plugin_id: str,
        inputs: Dict[str, Any],
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Execute plugin in controlled manner.

        Args:
            plugin_id: Plugin to execute
            inputs: Input data
            context: Execution context

        Returns:
            Execution result with artifacts
        """
        plugin = await self.get_plugin(plugin_id)
        if not plugin:
            raise ValueError(f"Plugin not found: {plugin_id}")

        # Update stats
        plugin.execution_count += 1

        try:
            # Load skill class
            skill_class = plugin.get_skill_class()
            skill_instance = skill_class()

            # Execute
            result = skill_instance.execute(inputs, context)

            # Update success count
            if result.success:
                plugin.success_count += 1

            return {
                "success": result.success,
                "data": result.data,
                "artifacts": result.artifacts,
                "error": result.error if not result.success else None
            }

        except Exception as e:
            logger.error(
                "mcp_plugin_execution_failed",
                plugin_id=plugin_id,
                error=str(e),
                exc_info=True
            )
            return {
                "success": False,
                "error": str(e),
                "artifacts": []
            }

    def _build_generation_prompt(
        self,
        capabilities: List[str],
        requirements: Dict[str, Any],
        goal_context: Optional[Dict] = None
    ) -> str:
        """Build detailed prompt for LLM skill generation."""

        capabilities_str = ", ".join(capabilities)
        goal_desc = goal_context.get("description", "") if goal_context else ""
        goal_title = goal_context.get("title", "") if goal_context else ""

        return f"""You are MCP (Modular Capability Plugin) skill generator for AI-OS.

Generate a Python skill plugin with these capabilities:
{capabilities_str}

Context:
- Goal: {goal_title}
- Description: {goal_desc}
- Input Type: {requirements.get('input_type', 'text')}
- Output Type: {requirements.get('output_type', 'text')}
- Required Artifacts: {requirements.get('artifacts', [])}

The skill MUST follow this structure:

```python
from canonical_skills.base import Skill, SkillResult, Artifact
from logging_config import get_logger

logger = get_logger(__name__)

class GeneratedCapabilitySkill(Skill):
    \"\"\"Auto-generated skill for {capabilities_str}\"\"\"

    id = "{self._generate_skill_id(capabilities)}"
    version = "0.1.0"

    def execute(self, inputs, context):
        \"\"\"Execute {capabilities_str} operation.\"\"\"
        try:
            # IMPLEMENT YOUR LOGIC HERE
            # inputs is a dict with input data
            # context contains goal_id, user_id, etc.

            result_data = inputs.get('text', '')

            # Return success with artifacts
            return SkillResult(
                success=True,
                data=result_data,
                artifacts=[
                    Artifact(
                        type="FILE",
                        content_kind="text",
                        content_location="output.txt",
                        description="Generated output"
                    )
                ]
            )
        except Exception as e:
            logger.error("skill_execution_failed", error=str(e), exc_info=True)
            return SkillResult(
                success=False,
                error=str(e),
                artifacts=[]
            )
```

IMPORTANT REQUIREMENTS:
1. skill_id must be lowercase_with_underscores (e.g., "web_scraper", "data_analyzer")
2. Include proper error handling with try/except
3. Always return SkillResult with success, data, artifacts
4. Log key execution steps
5. Implement actual logic for the requested capabilities

Generate only the Python class code, no explanation.
"""

    def _generate_skill_id(self, capabilities: List[str]) -> str:
        """Generate skill ID from capabilities."""
        if not capabilities:
            return "auto_generated_skill"

        # Take first capability and convert to snake_case
        primary = capabilities[0].lower().replace("-", "_").replace(" ", "_")
        return f"{primary}_skill"

    async def _llm_generate(self, prompt: str) -> str:
        """Generate skill code via LLM."""
        try:
            response = await chat_with_fallback(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                model=self.GENERATION_MODEL
            )

            # Extract content from response (OpenAI format)
            if isinstance(response, dict):
                # Try OpenAI format first
                if 'choices' in response and len(response['choices']) > 0:
                    content = response['choices'][0].get('message', {}).get('content')
                    if content:
                        return content
                # Fallback to direct content field
                elif 'content' in response:
                    return response['content']
                else:
                    # Last resort: stringify
                    logger.warning(
                        "mcp_unexpected_response_format",
                        keys=list(response.keys())
                    )
                    return str(response)
            elif isinstance(response, str):
                return response
            else:
                logger.warning(
                    "mcp_unexpected_response_type",
                    type=type(response).__name__
                )
                return str(response)

        except Exception as e:
            logger.error("mcp_llm_generation_failed", error=str(e))
            raise

    def _extract_skill_class(self, code: str) -> str:
        """Extract clean skill class code from LLM response."""
        # Remove markdown code blocks
        if "```python" in code:
            start = code.find("```python") + 9
            end = code.find("```", start)
            if end > start:
                code = code[start:end]
        elif "```" in code:
            start = code.find("```") + 3
            end = code.find("```", start)
            if end > start:
                code = code[start:end]

        return code.strip()

    def _extract_plugin_id(self, code: str) -> Optional[str]:
        """Extract plugin_id from class definition."""
        # Find id = "..." pattern
        match = re.search(r'id\s*=\s*["\']([^"\']+)["\']', code)
        if match:
            return match.group(1)

        # Try to infer from class name
        class_match = re.search(r'class\s+(\w+)\(Skill\)', code)
        if class_match:
            class_name = class_match.group(1)
            # Convert CamelCase to snake_case
            plugin_id = re.sub(r'(?<!^)(?=[A-Z])', '_', class_name).lower()
            return plugin_id

        return None

    async def _check_plugin_cap(self):
        """Check if we've hit the plugin limit."""
        async with AsyncSessionLocal() as session:
            count_stmt = select(func.count(AutogeneratedSkill.id))
            count_result = await session.execute(count_stmt)
            total_count = count_result.scalar() or 0

            if total_count >= self.MAX_PLUGINS:
                logger.warning(
                    "mcp_max_plugins_reached",
                    current=total_count,
                    cap=self.MAX_PLUGINS
                )
                raise Exception(f"Max MCP plugins reached ({self.MAX_PLUGINS})")

    async def _check_rate_limit(self):
        """Check if we should rate limit skill generation."""
        # Check concurrent generations
        if len(self._active_generations) >= self.MAX_CONCURRENT_GENERATIONS:
            logger.warning(
                "mcp_rate_limit_concurrent",
                active=len(self._active_generations),
                max=self.MAX_CONCURRENT_GENERATIONS
            )
            raise Exception(
                f"Too many concurrent skill generations ({len(self._active_generations)}). "
                f"Max: {self.MAX_CONCURRENT_GENERATIONS}"
            )

        # Check cooldown between generations
        if self._last_generation_time:
            time_since_last = (datetime.utcnow() - self._last_generation_time).total_seconds()
            if time_since_last < self.GENERATION_COOLDOWN_SECONDS:
                logger.warning(
                    "mcp_rate_limit_cooldown",
                    time_since_last_s=time_since_last,
                    min_cooldown_s=self.GENERATION_COOLDOWN_SECONDS
                )
                raise Exception(
                    f"Skill generation cooldown active. "
                    f"Please wait {self.GENERATION_COOLDOWN_SECONDS - time_since_last:.0f}s"
                )

        # Try to prune old skills before hitting the cap
        await self._prune_old_skills()

    async def _prune_old_skills(self):
        """Remove old/unused skills to prevent skill explosion."""
        from datetime import timedelta

        pruned_count = 0

        for plugin_id, plugin in list(self._registry.items()):
            # Skip recently created skills
            if plugin.created_at > datetime.utcnow() - timedelta(days=self.PRUNING_THRESHOLD_DAYS):
                continue

            # Skip skills with recent usage
            if plugin.execution_count >= self.MIN_EXECUTIONS_BEFORE_PRUNING:
                # Check success rate
                if plugin.success_rate >= self.MIN_SUCCESS_RATE_FOR_RETENTION:
                    continue  # Keep useful skills

            # Prune this skill
            logger.info(
                "mcp_pruning_skill",
                plugin_id=plugin_id,
                execution_count=plugin.execution_count,
                success_rate=plugin.success_rate,
                age_days=(datetime.utcnow() - plugin.created_at).days
            )

            # Remove from registry
            del self._registry[plugin_id]

            # Delete file
            plugin_path = self.plugins_dir / f"{plugin_id}.py"
            if plugin_path.exists():
                plugin_path.unlink()

            # Update database status
            await self._mark_skill_deprecated(plugin_id)

            pruned_count += 1

        if pruned_count > 0:
            logger.info(
                "mcp_pruning_complete",
                pruned_count=pruned_count,
                remaining=len(self._registry)
            )

    async def _mark_skill_deprecated(self, plugin_id: str):
        """Mark skill as deprecated in database."""
        from sqlalchemy import update
        from autogenerated_skill_models import AutogeneratedSkill

        async with AsyncSessionLocal() as session:
            stmt = update(AutogeneratedSkill).where(
                AutogeneratedSkill.skill_id == plugin_id
            ).values(status="deprecated")

            await session.execute(stmt)
            await session.commit()

    async def _sandbox_validate(
        self,
        plugin_path: str,
        plugin_id: str
    ) -> Dict[str, Any]:
        """
        Validate plugin in sandbox.

        Checks:
        1. Syntax validity
        2. Required attributes (id, execute)
        3. Safety (no dangerous commands)
        4. Mock execution test

        Returns:
            {"passed": bool, "errors": str}
        """
        # Check 1: Syntax
        try:
            spec = importlib.util.spec_from_file_location(plugin_id, plugin_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
        except SyntaxError as e:
            return {
                "passed": False,
                "errors": f"Syntax error: {str(e)}"
            }
        except Exception as e:
            return {
                "passed": False,
                "errors": f"Import error: {str(e)}"
            }

        # Check 2: Required attributes
        try:
            from canonical_skills.base import Skill as BaseSkill
            skill_class_found = False

            for attr_name in dir(module):
                # Skip private attributes and base Skill class
                if attr_name.startswith('_') or attr_name == 'Skill':
                    continue

                attr = getattr(module, attr_name)
                if isinstance(attr, type) and attr_name.endswith('Skill'):
                    # Skip base Skill class
                    if attr is BaseSkill or attr.__name__ == 'Skill':
                        continue

                    skill_class_found = True

                    # Check for 'id' attribute (use getattr to get actual class attribute)
                    class_id = getattr(attr, 'id', None)
                    if not class_id or not isinstance(class_id, str):
                        logger.warning(
                            "mcp_validation_failed_id",
                            class_name=attr_name,
                            has_id=hasattr(attr, 'id'),
                            id_value=class_id,
                            id_type=type(class_id).__name__ if class_id else None
                        )
                        return {"passed": False, "errors": f"Missing or invalid 'id' attribute in {attr_name}"}

                    # Check for 'execute' method
                    if not hasattr(attr, 'execute'):
                        return {"passed": False, "errors": "Missing 'execute' method"}

                    logger.info(
                        "mcp_skill_class_found",
                        class_name=attr_name,
                        skill_id=class_id
                    )
                    break

            if not skill_class_found:
                logger.warning("mcp_no_skill_class_found", module_attrs=[a for a in dir(module) if not a.startswith('_')])
                return {"passed": False, "errors": "No Skill class found"}
        except Exception as e:
            logger.error("mcp_structure_validation_error", error=str(e), exc_info=True)
            return {
                "passed": False,
                "errors": f"Structure validation error: {str(e)}"
            }

        # Check 3: Safety
        if not self._check_safety(plugin_path):
            return {
                "passed": False,
                "errors": "Safety check failed (dangerous patterns detected)"
            }

        # Check 4: Mock execution (basic smoke test)
        try:
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if isinstance(attr, type) and attr_name.endswith('Skill'):
                    skill_instance = attr()
                    # Try mock execution with empty input
                    result = skill_instance.execute({}, {})
                    if not hasattr(result, 'success'):
                        return {"passed": False, "errors": "execute() doesn't return SkillResult"}
                    break
        except Exception as e:
            # Mock execution failed, but plugin might still work with real input
            logger.warning(
                "mcp_mock_execution_failed",
                plugin_id=plugin_id,
                error=str(e)
            )

        return {"passed": True}

    def _check_safety(self, plugin_path: str) -> bool:
        """Check for dangerous command patterns."""
        dangerous_patterns = [
            'rm -rf',
            'format c:',
            'DROP DATABASE',
            'TRUNCATE',
            '__import__("os").system',
            'eval(',
            'exec(',
            'subprocess.call'
        ]

        with open(plugin_path, 'r') as f:
            code = f.read()

        for pattern in dangerous_patterns:
            if pattern in code:
                logger.warning(
                    "mcp_dangerous_pattern_found",
                    pattern=pattern,
                    path=plugin_path
                )
                return False

        return True

    async def _save_to_database(
        self,
        plugin: MCPSkillPlugin,
        validation_result: Dict[str, Any]
    ):
        """Save plugin metadata to database."""
        async with AsyncSessionLocal() as session:
            autogenerated = AutogeneratedSkill(
                skill_id=plugin.plugin_id,
                version=plugin.version,
                generation_trigger="missing_capability",
                llm_model=self.GENERATION_MODEL,
                validation_status="passed" if validation_result["passed"] else "failed",
                validation_errors=validation_result.get("errors"),
                status=plugin.status
            )

            session.add(autogenerated)
            await session.commit()


# Singleton instance
mcp_skill_generator = MCPSkillGenerator()
