"""
SKILL AUTO-GENERATOR - Self-improving skill system for AI-OS
===========================================================

This module enables AI-OS to automatically generate new skills when needed.

Flow:
1. Goal arrives → Check if skill exists
2. If not → Generate skill stub
3. Validate → Sandbox test
4. Register with "experimental" status
5. Execute → Monitor
6. Improve based on execution logs

Author: AI-OS System
"""

import os
import re
import importlib
import importlib.util
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class SkillGap:
    """Represents a missing skill capability."""
    capability: str
    goal_type: str
    frequency: int  # How often this gap was detected


@dataclass
class GeneratedSkill:
    """Represents an auto-generated skill."""
    id: str
    name: str
    capabilities: List[str]
    requirements: List[str]
    code: str
    status: str  # "experimental", "validated", "failed"


class SkillAutogenerator:
    """
    Auto-generates skills when needed.
    
    Usage:
        generator = SkillAutogenerator()
        gap = generator.detect_gap(goal)
        if gap:
            skill = generator.generate(gap)
            if generator.validate(skill):
                generator.register(skill)
    """
    
    def __init__(self):
        self.autogenerated_dir = Path("/app/canonical_skills/autogenerated")
        self.autogenerated_dir.mkdir(exist_ok=True)
        
    def detect_gap(self, goal_title: str, goal_type: str = "achievable") -> Optional[SkillGap]:
        """
        Detect if a skill is missing for this goal.
        
        Args:
            goal_title: Goal title/description
            goal_type: Type of goal
            
        Returns:
            SkillGap if gap detected, None otherwise
        """
        # Import here to avoid circular dependencies
        from canonical_skills.registry import skill_registry
        
        # Extract capabilities from goal
        required_caps = self._extract_capabilities(goal_title)
        
        if not required_caps:
            return None
            
        # Check existing skills
        existing_caps = set()
        for skill in skill_registry.list():
            existing_caps.update(getattr(skill, 'capabilities', []))
        
        # Find missing capabilities
        missing = [cap for cap in required_caps if cap not in existing_caps]
        
        if missing:
            gap = SkillGap(
                capability=missing[0],  # Take first missing
                goal_type=goal_type,
                frequency=1
            )
            logger.info("skill_gap_detected", capability=gap.capability, goal_type=goal_type)
            return gap
            
        return None
    
    def _extract_capabilities(self, text: str) -> List[str]:
        """Extract required capabilities from goal text."""
        text_lower = text.lower()
        capabilities = []
        
        # Keyword to capability mapping
        capability_map = {
            "search": "search",
            "find": "search",
            "research": "research",
            "analyze": "analyze",
            "extract": "extract",
            "summarize": "summarize",
            "write": "file-write",
            "create": "file-write",
            "read": "file-read",
            "list": "file-list",
            "delete": "file-delete",
            "run": "execute",
            "execute": "execute",
            "command": "execute",
            "api": "api-call",
            "http": "api-call",
            "database": "database",
            "sql": "database",
            "test": "testing",
            "validate": "validation",
            "convert": "convert",
            "transform": "convert",
            "encrypt": "security",
            "compress": "compress",
            "email": "communication",
            "send": "communication",
        }
        
        for keyword, capability in capability_map.items():
            if keyword in text_lower and capability not in capabilities:
                capabilities.append(capability)
        
        return capabilities
    
    def generate(self, gap: SkillGap) -> GeneratedSkill:
        """
        Generate a new skill stub for the gap.
        
        Args:
            gap: The skill gap to fill
            
        Returns:
            Generated skill with basic implementation
        """
        skill_id = f"auto.{gap.capability}"
        skill_name = f"AutoGenerated{gap.capability.title().replace('-', '')}Skill"
        
        # Generate skill code
        code = self._generate_skill_code(skill_id, skill_name, gap.capability)
        
        skill = GeneratedSkill(
            id=skill_id,
            name=skill_name,
            capabilities=[gap.capability],
            requirements=[],
            code=code,
            status="experimental"
        )
        
        logger.info("skill_generated", skill_id=skill_id, capability=gap.capability)
        
        # Save to file
        self._save_skill(skill)
        
        return skill
    
    def _generate_skill_code(self, skill_id: str, skill_name: str, capability: str) -> str:
        """Generate Python code for the skill."""
        
        template = f'''"""
AUTO-GENERATED SKILL - {capability}
Generated automatically by AI-OS Skill Autogenerator

⚠️ STATUS: Experimental
This skill was auto-generated and may need improvement.
"""
from canonical_skills.base import Skill, SkillResult, Artifact


class {skill_name}(Skill):
    """Auto-generated skill for {capability} capability."""
    
    id = "{skill_id}"
    version = "0.1.0"
    description = "Auto-generated skill for {capability}"
    
    capabilities = ["{capability}"]
    requirements = []
    
    input_schema = {{
        "type": "object",
        "properties": {{
            "data": {{"type": "string", "description": "Input data"}}
        }},
        "required": ["data"]
    }}
    
    output_schema = {{
        "type": "object",
        "properties": {{
            "result": {{"type": "string"}}
        }}
    }}
    
    produces_artifacts = ["KNOWLEDGE"]
    
    def execute(self, input_data: dict, context: dict) -> SkillResult:
        """
        Execute {capability} operation.
        
        TODO: Implement actual logic for {capability}
        Currently returns a stub result for testing.
        """
        data = input_data.get("data", "")
        
        # Basic implementation - can be improved via skill_improver
        result_text = f"Processed {{data[:100]}} with {{capability}}"
        
        artifact = self._artifact(
            type_="KNOWLEDGE",
            content=result_text,
            metadata={{
                "source": "{skill_name}",
                "capability": "{capability}",
                "status": "experimental"
            }}
        )
        
        output = {{
            "result": result_text,
            "capability": "{capability}"
        }}
        
        return self._success_result(output, [artifact])
    
    def verify(self, result: SkillResult) -> bool:
        """Verify skill result."""
        return result.success and len(result.artifacts) > 0
'''
        return template

    def _extract_class_name(self, skill_code: str) -> str:
        """Extract skill class name from code"""
        # Find class definition
        import re
        match = re.search(r'class\s+(\w+)\s*\(\s*Skill\s*\):', skill_code)
        if match:
            return match.group(1)
        # Fallback: try to find any class that inherits from Skill
        match = re.search(r'class\s+(\w+).*:', skill_code)
        if match:
            return match.group(1)
        # Ultimate fallback
        return "GeneratedSkill"

    def _save_skill(self, skill: GeneratedSkill):
        """Save generated skill to file."""
        filename = f"{skill.id.replace('.', '_')}.py"
        filepath = self.autogenerated_dir / filename

        with open(filepath, 'w') as f:
            f.write(skill.code)

        logger.info("skill_saved", path=str(filepath))
    
    async def validate(self, skill: GeneratedSkill) -> bool:
        """
        Validate generated skill before registration using SANDBOX testing.

        NEW v2.0: Now uses SandboxSkillValidator for comprehensive testing.

        Validation Pipeline:
        1. Syntax validity
        2. Security check (forbidden operations)
        3. Import test (can module be loaded?)
        4. Instantiation test (can skill class be created?)
        5. Execution test (does skill execute correctly?)
        6. Artifact verification (does skill return SkillResult with artifacts?)
        """
        from skill_sandbox_validator import get_skill_validator

        # Extract skill class name from code
        skill_name = self._extract_class_name(skill.code)

        # Use sandbox validator
        validator = get_skill_validator()
        report = await validator.validate(
            skill_code=skill.code,
            skill_id=skill.id,
            skill_name=skill_name
        )

        if not report.is_valid:
            logger.error(
                "skill_validation_failed",
                skill_id=skill.id,
                result=report.result.value,
                errors=report.errors,
                warnings=report.warnings
            )
            skill.status = "failed"
            return False

        logger.info(
            "skill_validated_complete",
            skill_id=skill.id,
            skill_name=skill_name,
            tests_passed=report.to_dict()["tests"],
            duration_ms=report.execution_time_ms
        )
        skill.status = "validated"
        return True
    
    def register(self, skill: GeneratedSkill) -> bool:
        """
        Register validated skill in the registry.
        
        Args:
            skill: Validated skill to register
            
        Returns:
            True if registered successfully
        """
        # Import modules dynamically
        import sys
        from importlib.util import module_from_spec, spec_from_loader
        from canonical_skills.base import Skill
        
        # Add autogenerated dir to path
        if str(self.autogenerated_dir) not in sys.path:
            sys.path.insert(0, str(self.autogenerated_dir))
        
        try:
            # Load module
            module_name = skill.id.replace('.', '_')
            spec = importlib.util.spec_from_file_location(
                module_name, 
                self.autogenerated_dir / f"{module_name}.py"
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            
            # Find skill class
            skill_class = None
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if isinstance(attr, type) and issubclass(attr, Skill) and attr != Skill:
                    skill_class = attr
                    break
            
            if not skill_class:
                logger.error("skill_class_not_found", skill_id=skill.id)
                return False
            
            # Register in canonical registry
            from canonical_skills.registry import skill_registry
            skill_instance = skill_class()
            skill_registry.register(skill_instance)
            
            logger.info("skill_registered", skill_id=skill.id, version=skill.version)
            return True
            
        except Exception as e:
            logger.error("skill_registration_failed", skill_id=skill.id, error=str(e))
            return False
    
    def improve(self, skill_id: str, execution_logs: List[Dict]) -> bool:
        """
        Improve skill based on execution logs.
        
        Args:
            skill_id: ID of skill to improve
            execution_logs: List of execution results
            
        Returns:
            True if improved successfully
        """
        logger.info("skill_improvement_started", skill_id=skill_id, logs_count=len(execution_logs))
        
        # Analyze failures
        failures = [log for log in execution_logs if not log.get('success', True)]
        
        if not failures:
            logger.info("skill_no_improvement_needed", skill_id=skill_id)
            return True
        
        # TODO: Use LLM to generate improved code
        # For now, just log the improvement need
        logger.info("skill_improvement_needed", skill_id=skill_id, failures=len(failures))
        
        return True


class SkillImprover:
    """
    Improves skills based on execution feedback.
    
    Uses LLM to analyze failures and generate improvements.
    """
    
    def __init__(self):
        pass
    
    def analyze_failure(self, skill_id: str, error: str, context: Dict) -> str:
        """
        Analyze why a skill failed and suggest improvement.
        
        Returns:
            Improvement suggestion
        """
        # Simple analysis - could use LLM for more sophisticated analysis
        if "not implemented" in error.lower():
            return f"Implement {skill_id} logic for {context.get('capability', 'unknown')}"
        
        if "timeout" in error.lower():
            return f"Add timeout handling to {skill_id}"
        
        return f"Review and fix {skill_id}: {error[:100]}"


# Global instance
_skill_autogenerator = None


def get_skill_autogenerator() -> SkillAutogenerator:
    """Get global skill autogenerator instance."""
    global _skill_autogenerator
    if _skill_autogenerator is None:
        _skill_autogenerator = SkillAutogenerator()
    return _skill_autogenerator


# Integration helper
async def check_and_generate_skill(goal_title: str, goal_type: str = "achievable") -> Optional[GeneratedSkill]:
    """
    Check if skill exists for goal, generate if missing.

    UPDATED v2.0: Now uses async validation with sandbox testing.

    Usage:
        skill = await check_and_generate_skill("Research AI trends", "achievable")
        if skill:
            # Skill was auto-generated, validated in sandbox, and registered
            pass
    """
    generator = get_skill_autogenerator()

    # Detect gap
    gap = generator.detect_gap(goal_title, goal_type)
    if not gap:
        return None

    # Generate skill
    skill = generator.generate(gap)

    # Validate (NOW WITH SANDBOX TESTING)
    if not await generator.validate(skill):
        return None

    # Register
    if generator.register(skill):
        return skill

    return None
