"""
SKILL SANDBOX VALIDATOR - Safe skill testing before registration
================================================================

Tests auto-generated skills in isolated sandbox environment before
allowing them into the production skill registry.

CRITICAL: This prevents buggy/malicious skills from breaking the system.

Validation Pipeline:
1. Syntax check - Python compilation
2. Import test - Can module be imported?
3. Instantiation test - Can skill class be created?
4. Execution test - Does skill execute in sandbox?
5. Artifact verification - Does skill return valid SkillResult?
6. Security check - No forbidden operations

Author: AI-OS Core Team
Date: 2026-03-09
Version: 1.0.0
"""
import os
import re
import subprocess
import tempfile
import asyncio
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from enum import Enum

from logging_config import get_logger

logger = get_logger(__name__)


class ValidationResult(str, Enum):
    """Skill validation result"""
    PASSED = "passed"
    FAILED = "failed"
    TIMEOUT = "timeout"
    SECURITY_VIOLATION = "security_violation"


@dataclass
class ValidationReport:
    """Complete validation report for a skill"""
    skill_id: str
    skill_name: str
    result: ValidationResult

    # Individual test results
    syntax_check: bool
    import_test: bool
    instantiation_test: bool
    execution_test: bool
    artifact_check: bool
    security_check: bool

    # Details
    errors: List[str]
    warnings: List[str]
    execution_time_ms: int

    # Sandbox resource usage
    tokens_used: int = 0
    memory_mb: int = 0

    @property
    def is_valid(self) -> bool:
        """Overall validation status"""
        return self.result == ValidationResult.PASSED

    def to_dict(self) -> Dict:
        return {
            "skill_id": self.skill_id,
            "skill_name": self.skill_name,
            "result": self.result.value,
            "is_valid": self.is_valid,
            "tests": {
                "syntax": self.syntax_check,
                "import": self.import_test,
                "instantiation": self.instantiation_test,
                "execution": self.execution_test,
                "artifacts": self.artifact_check,
                "security": self.security_check
            },
            "errors": self.errors,
            "warnings": self.warnings,
            "execution_time_ms": self.execution_time_ms,
            "resource_usage": {
                "tokens": self.tokens_used,
                "memory_mb": self.memory_mb
            }
        }


class SandboxSkillValidator:
    """
    Validate skills in isolated sandbox environment.

    Uses OCCP Sandbox contract system for safe execution.
    """

    # Dangerous patterns that will FAIL validation
    FORBIDDEN_PATTERNS = [
        r'rm\s+-rf\s+/',           # Delete root filesystem
        r'format\s+C:',             # Format Windows drive
        r'shutil\.rmtree\(/',       # Delete root directory
        r'os\.system\(',            # Arbitrary command execution
        r'subprocess\.call\(',      # Alternative command execution
        r'eval\s*\(',               # Code evaluation
        r'exec\s*\(',               # Code execution
        r'__import__\(',            # Hidden imports
        r'compile\s*\(',            # Code compilation
        r'open\s*\([^)]*w',         # File write mode
    ]

    # Required skill class attributes
    REQUIRED_ATTRIBUTES = [
        'id',
        'version',
        'description',
        'execute',
    ]

    def __init__(self, autogenerated_dir: str = "/app/canonical_skills/autogenerated"):
        self.autogenerated_dir = Path(autogenerated_dir)
        self.autogenerated_dir.mkdir(exist_ok=True, parents=True)

    async def validate(
        self,
        skill_code: str,
        skill_id: str,
        skill_name: str
    ) -> ValidationReport:
        """
        Validate skill through complete testing pipeline.

        Args:
            skill_code: Python code for the skill
            skill_id: Unique skill identifier
            skill_name: Name of the skill class

        Returns:
            ValidationReport with complete test results
        """
        import time
        start_time = time.time()

        report = ValidationReport(
            skill_id=skill_id,
            skill_name=skill_name,
            result=ValidationResult.FAILED,
            syntax_check=False,
            import_test=False,
            instantiation_test=False,
            execution_test=False,
            artifact_check=False,
            security_check=False,
            errors=[],
            warnings=[],
            execution_time_ms=0
        )

        # Test 1: Syntax validation
        if not self._validate_syntax(skill_code, report):
            return report

        # Test 2: Security check
        if not self._validate_security(skill_code, report):
            report.result = ValidationResult.SECURITY_VIOLATION
            return report

        # Write skill to temp file for testing
        with tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.py',
            delete=False,
            dir=self.autogenerated_dir
        ) as f:
            f.write(skill_code)
            temp_path = f.name

        try:
            # Test 3: Import test
            if not await self._test_import(temp_path, skill_id, report):
                return report

            # Test 4: Instantiation test
            if not await self._test_instantiation(
                temp_path, skill_name, skill_id, report
            ):
                return report

            # Test 5: Execution test in sandbox
            if not await self._test_execution(
                temp_path, skill_name, skill_id, report
            ):
                return report

            # All tests passed!
            report.result = ValidationResult.PASSED
            report.execution_time_ms = int((time.time() - start_time) * 1000)

            logger.info(
                "skill_validation_passed",
                skill_id=skill_id,
                skill_name=skill_name,
                duration_ms=report.execution_time_ms
            )

            return report

        finally:
            # Cleanup temp file
            try:
                if os.path.exists(temp_path):
                    os.unlink(temp_path)
            except Exception as e:
                logger.warning(
                    "skill_cleanup_failed",
                    skill_id=skill_id,
                    error=str(e)
                )

    def _validate_syntax(self, code: str, report: ValidationReport) -> bool:
        """Test 1: Validate Python syntax"""
        try:
            compile(code, '<string>', 'exec')
            report.syntax_check = True
            return True
        except SyntaxError as e:
            report.syntax_check = False
            report.errors.append(f"Syntax error at line {e.lineno}: {e.msg}")
            logger.error(
                "skill_syntax_invalid",
                skill_id=report.skill_id,
                line=e.lineno,
                error=e.msg
            )
            return False

    def _validate_security(self, code: str, report: ValidationReport) -> bool:
        """Test 2: Check for forbidden operations"""
        violations = []

        for pattern in self.FORBIDDEN_PATTERNS:
            if re.search(pattern, code):
                violations.append(f"Forbidden pattern: {pattern}")

        if violations:
            report.security_check = False
            report.errors.extend(violations)
            logger.error(
                "skill_security_violation",
                skill_id=report.skill_id,
                violations=violations
            )
            return False

        report.security_check = True
        return True

    async def _test_import(
        self,
        skill_path: str,
        skill_id: str,
        report: ValidationReport
    ) -> bool:
        """Test 3: Can the skill module be imported?"""
        try:
            result = subprocess.run(
                ["python", "-c", self._import_test_code(skill_path)],
                capture_output=True,
                timeout=10,
                text=True,
                cwd=str(self.autogenerated_dir)
            )

            if result.returncode == 0:
                report.import_test = True
                return True
            else:
                report.import_test = False
                error_msg = result.stderr[:500] if result.stderr else "Unknown error"
                report.errors.append(f"Import failed: {error_msg}")
                logger.error(
                    "skill_import_failed",
                    skill_id=skill_id,
                    error=error_msg
                )
                return False

        except subprocess.TimeoutExpired:
            report.import_test = False
            report.errors.append("Import test timeout (>10s)")
            report.result = ValidationResult.TIMEOUT
            return False
        except Exception as e:
            report.import_test = False
            report.errors.append(f"Import test error: {str(e)}")
            return False

    async def _test_instantiation(
        self,
        skill_path: str,
        skill_name: str,
        skill_id: str,
        report: ValidationReport
    ) -> bool:
        """Test 4: Can the skill class be instantiated?"""
        try:
            test_code = self._instantiation_test_code(skill_path, skill_name)
            result = subprocess.run(
                ["python", "-c", test_code],
                capture_output=True,
                timeout=10,
                text=True,
                cwd=str(self.autogenerated_dir)
            )

            if result.returncode == 0 and "SUCCESS" in result.stdout:
                report.instantiation_test = True
                return True
            else:
                report.instantiation_test = False
                error_msg = result.stderr[:500] if result.stderr else "Unknown error"
                report.errors.append(f"Instantiation failed: {error_msg}")
                logger.error(
                    "skill_instantiation_failed",
                    skill_id=skill_id,
                    error=error_msg
                )
                return False

        except subprocess.TimeoutExpired:
            report.instantiation_test = False
            report.errors.append("Instantiation test timeout (>10s)")
            report.result = ValidationResult.TIMEOUT
            return False
        except Exception as e:
            report.instantiation_test = False
            report.errors.append(f"Instantiation test error: {str(e)}")
            return False

    async def _test_execution(
        self,
        skill_path: str,
        skill_name: str,
        skill_id: str,
        report: ValidationReport
    ) -> bool:
        """Test 5: Does skill execute correctly and return valid SkillResult?"""
        try:
            test_code = self._execution_test_code(skill_path, skill_name)
            result = subprocess.run(
                ["python", "-c", test_code],
                capture_output=True,
                timeout=15,
                text=True,
                cwd=str(self.autogenerated_dir)
            )

            output = result.stdout + result.stderr

            # Check for success markers
            if "EXECUTION_SUCCESS" in output:
                report.execution_test = True

                # Check for artifacts
                if "ARTIFACT_FOUND" in output:
                    report.artifact_check = True
                else:
                    report.artifact_check = False
                    report.warnings.append("Skill executed but returned no artifacts")
                    logger.warning(
                        "skill_no_artifacts",
                        skill_id=skill_id
                    )

                return True
            else:
                report.execution_test = False
                report.artifact_check = False
                error_msg = output[:500]
                report.errors.append(f"Execution failed: {error_msg}")
                logger.error(
                    "skill_execution_failed",
                    skill_id=skill_id,
                    error=error_msg
                )
                return False

        except subprocess.TimeoutExpired:
            report.execution_test = False
            report.artifact_check = False
            report.errors.append("Execution test timeout (>15s)")
            report.result = ValidationResult.TIMEOUT
            return False
        except Exception as e:
            report.execution_test = False
            report.artifact_check = False
            report.errors.append(f"Execution test error: {str(e)}")
            return False

    def _import_test_code(self, skill_path: str) -> str:
        """Generate Python code for import test"""
        return f"""
import importlib.util
spec = importlib.util.spec_from_file_location('test_skill', '{skill_path}')
if spec is None:
    print("IMPORT_FAILED: spec is None")
    import sys
    sys.exit(1)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
print("IMPORT_SUCCESS")
"""

    def _instantiation_test_code(self, skill_path: str, skill_name: str) -> str:
        """Generate Python code for instantiation test"""
        return f"""
import sys
import importlib.util

# Add autogenerated dir to path
sys.path.insert(0, '{self.autogenerated_dir}')

# Import module
spec = importlib.util.spec_from_file_location('skill', '{skill_path}')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

# Get skill class
skill_cls = getattr(module, '{skill_name}')
if skill_cls is None:
    print("INSTANTIATION_FAILED: class not found")
    import sys
    sys.exit(1)

# Check required attributes
required = {self.REQUIRED_ATTRIBUTES}
missing = [attr for attr in required if not hasattr(skill_cls, attr)]
if missing:
    print(f"INSTANTIATION_FAILED: missing attributes: {{missing}}")
    import sys
    sys.exit(1)

# Try to instantiate
try:
    skill = skill_cls()
    print("SUCCESS")
except Exception as e:
    print(f"INSTANTIATION_FAILED: {{e}}")
    import sys
    sys.exit(1)
"""

    def _execution_test_code(self, skill_path: str, skill_name: str) -> str:
        """Generate Python code for execution test"""
        return f"""
import sys
import json
sys.path.insert(0, '{self.autogenerated_dir}')

# Import and instantiate
import importlib.util
spec = importlib.util.spec_from_file_location('skill', '{skill_path}')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

skill_cls = getattr(module, '{skill_name}')
skill = skill_cls()

# Execute with test input
try:
    result = skill.execute(
        input_data={{"data": "test_input"}},
        context={{"test": True}}
    )

    # Check if result is SkillResult
    if hasattr(result, 'success') and hasattr(result, 'artifacts'):
        if result.success and len(result.artifacts) > 0:
            print("EXECUTION_SUCCESS")
            print("ARTIFACT_FOUND")
            print(f"Artifact count: {{len(result.artifacts)}}")
        elif result.success:
            print("EXECUTION_SUCCESS")
            print("WARNING: No artifacts returned")
        else:
            print("EXECUTION_FAILED: success=False")
    else:
        print("EXECUTION_FAILED: invalid result type")

except Exception as e:
    print(f"EXECUTION_FAILED: {{str(e)}}")
    import traceback
    traceback.print_exc()
"""


# Global validator instance
_validator: Optional[SandboxSkillValidator] = None


def get_skill_validator() -> SandboxSkillValidator:
    """Get global skill validator instance"""
    global _validator
    if _validator is None:
        _validator = SandboxSkillValidator()
    return _validator
