"""
Skill Autogenerator V2 - Generates new skills when missing capabilities detected

Minimal implementation:
- Detects missing skills
- Generates stub code via LLM
- Validates syntax
- Registers as experimental
"""
import os
import asyncio
from typing import List, Dict, Any, Optional
from pathlib import Path
from datetime import datetime
import re

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from database import AsyncSessionLocal
from llm_fallback import chat_with_fallback
from logging_config import get_logger
from autogenerated_skill_models import AutogeneratedSkill

logger = get_logger(__name__)


class SkillAutogenerator:
    """
    Generates new skills when required capabilities are missing.
    """

    # Configuration
    AUTOGENERATED_SKILLS_DIR = Path("/app/canonical_skills/autogenerated")
    MAX_AUTOGENERATED_SKILLS = 50

    def __init__(self):
        self.autogen_dir = self.AUTOGENERATED_SKILLS_DIR
        self.autogen_dir.mkdir(exist_ok=True)

    async def generate_skill(
        self,
        missing_capabilities: List[str],
        requirements: Dict[str, Any]
    ) -> str:
        """
        Generate a new skill for missing capabilities.

        Args:
            missing_capabilities: List of required capabilities
            requirements: Goal requirements (input_type, output_type, etc.)

        Returns:
            skill_id of generated skill
        """
        # Check cap
        async with AsyncSessionLocal() as session:
            count_stmt = select(func.count(AutogeneratedSkill.id))
            count_result = await session.execute(count_stmt)
            total_count = count_result.scalar() or 0

            if total_count >= self.MAX_AUTOGENERATED_SKILLS:
                logger.warning(
                    "max_autogenerated_skills_reached",
                    current=total_count,
                    cap=self.MAX_AUTOGENERATED_SKILLS
                )
                raise Exception("Max autogenerated skills reached")

        # Step 1: Build generation prompt
        prompt = self._build_generation_prompt(
            missing_capabilities,
            requirements
        )

        # Step 2: Generate code via LLM
        logger.info(
            "skill_generation_started",
            capabilities=missing_capabilities
        )

        skill_code = await self._llm_generate(prompt)

        # Step 3: Extract skill class
        skill_class_code = self._extract_skill_class(skill_code)
        skill_id = self._extract_skill_id(skill_class_code)

        if not skill_id:
            raise Exception("Could not extract skill_id from generated code")

        # Step 4: Save to file
        version = "0.1.0"
        skill_path = self.autogen_dir / f"{skill_id}.py"

        with open(skill_path, 'w') as f:
            f.write(skill_class_code)

        logger.info(
            "skill_code_saved",
            skill_id=skill_id,
            path=str(skill_path)
        )

        # Step 5: Validate
        validation_result = await self._validate_skill(skill_path)

        # Step 6: Save to database
        async with AsyncSessionLocal() as session:
            autogenerated = AutogeneratedSkill(
                skill_id=skill_id,
                version=version,
                generation_trigger="missing_capability",
                llm_model="local-coder",  # Ollama qwen2.5-coder
                validation_status=validation_result["status"],
                validation_errors=validation_result.get("errors"),
                status="experimental"
            )

            session.add(autogenerated)
            await session.commit()

            logger.info(
                "skill_autogenerated",
                skill_id=skill_id,
                validation_status=validation_result["status"]
            )

        if validation_result["status"] != "passed":
            raise Exception(f"Skill validation failed: {validation_result.get('errors')}")

        return skill_id

    def _build_generation_prompt(
        self,
        capabilities: List[str],
        requirements: Dict[str, Any]
    ) -> str:
        """Build prompt for LLM skill generation."""

        capabilities_str = ", ".join(capabilities)

        return f"""You are a skill generation system for AI-OS.

Generate a Python skill class with these capabilities:
{capabilities_str}

Requirements:
- Input: {requirements.get('input_type', 'text')}
- Output: {requirements.get('output_type', 'text')}
- Artifacts: {requirements.get('artifacts', [])}

The skill MUST:
1. Inherit from Skill in canonical_skills/base.py
2. Have an 'id' attribute (string, lowercase_with_underscores)
3. Have a 'version' attribute (string, default "0.1.0")
4. Implement execute(self, inputs, context) -> SkillResult
5. Return SkillResult with success, data, artifacts
6. Include proper error handling
7. Log execution steps using get_logger(__name__)

Available imports:
```python
from canonical_skills.base import Skill, SkillResult, Artifact
from logging_config import get_logger
```

Example structure:

```python
from canonical_skills.base import Skill, SkillResult, Artifact
from logging_config import get_logger

logger = get_logger(__name__)

class MyGeneratedSkill(Skill):
    id = "my_generated_skill"
    version = "0.1.0"

    def execute(self, inputs, context):
        try:
            # Your logic here
            result_data = inputs.get('text', '')

            return SkillResult(
                success=True,
                data=result_data,
                artifacts=[
                    Artifact(
                        type="FILE",
                        content_kind="text",
                        content_location="output.txt",
                        description="Generated output"
                    )
                ]
            )
        except Exception as e:
            logger.error("skill_execution_failed", error=str(e), exc_info=True)

            return SkillResult(
                success=False,
                error=str(e),
                artifacts=[]
            )
```

IMPORTANT:
- skill_id should be lowercase_with_underscores (e.g., "stock_analyzer")
- Include specific implementation for the requested capabilities
- Add proper error handling
- Log key steps

Generate only the Python class code, no explanation.
"""

    async def _llm_generate(self, prompt: str) -> str:
        """Generate skill code via LLM."""
        try:
            response = await chat_with_fallback(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                model="local-coder"  # Ollama qwen2.5-coder
            )

            # Extract content from response (OpenAI format)
            if isinstance(response, dict):
                # Try OpenAI format first
                if 'choices' in response and len(response['choices']) > 0:
                    content = response['choices'][0].get('message', {}).get('content')
                    if content:
                        return content
                # Fallback to direct content field
                elif 'content' in response:
                    return response['content']
                else:
                    # Last resort: stringify
                    return str(response)
            elif isinstance(response, str):
                return response
            else:
                return str(response)

        except Exception as e:
            logger.error("llm_generation_failed", error=str(e))
            raise

    def _extract_skill_class(self, code: str) -> str:
        """Extract the skill class from generated code."""
        # Remove markdown code blocks if present
        if "```python" in code:
            start = code.find("```python") + 9
            end = code.find("```", start)
            if end > start:
                code = code[start:end]
        elif "```" in code:
            start = code.find("```") + 3
            end = code.find("```", start)
            if end > start:
                code = code[start:end]

        return code.strip()

    def _extract_skill_id(self, code: str) -> Optional[str]:
        """Extract skill_id from class definition."""
        # Find id = "..." pattern
        match = re.search(r'id\s*=\s*["\']([^"\']+)["\']', code)
        if match:
            return match.group(1)

        # Try to infer from class name
        class_match = re.search(r'class\s+(\w+)\(Skill\)', code)
        if class_match:
            class_name = class_match.group(1)
            skill_id = re.sub(r'(?<!^)(?=[A-Z])', '_', class_name).lower()
            return skill_id

        return None

    async def _validate_skill(self, skill_path: str) -> Dict[str, Any]:
        """
        Validate generated skill.

        Returns:
            {"status": "passed"|"failed", "errors": "..."}
        """
        # Check 1: Syntax
        try:
            import importlib.util
            spec = importlib.util.spec_from_file_location("skill", skill_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
        except SyntaxError as e:
            return {
                "status": "failed",
                "errors": f"Syntax error: {str(e)}"
            }
        except Exception as e:
            return {
                "status": "failed",
                "errors": f"Import error: {str(e)}"
            }

        # Check 2: Required attributes
        try:
            skill_class = getattr(module, skill_path.stem.title().replace('_', ''))

            if not hasattr(skill_class, 'id'):
                return {"status": "failed", "errors": "Missing 'id' attribute"}

            if not hasattr(skill_class, 'execute'):
                return {"status": "failed", "errors": "Missing 'execute' method"}

        except Exception as e:
            return {
                "status": "failed",
                "errors": f"Structure validation error: {str(e)}"
            }

        # Check 3: Safety
        safety_check = self._check_safety(skill_path)
        if not safety_check:
            return {
                "status": "failed",
                "errors": "Safety check failed (dangerous patterns detected)"
            }

        return {"status": "passed"}

    def _check_safety(self, skill_path: str) -> bool:
        """Check for dangerous command patterns."""
        dangerous_patterns = [
            'rm -rf',
            'format c:',
            'DROP DATABASE',
            'TRUNCATE',
            '__import__("os").system',
            'eval(',
            'exec(',
            'subprocess.call'
        ]

        with open(skill_path, 'r') as f:
            code = f.read()

        for pattern in dangerous_patterns:
            if pattern in code:
                logger.warning(
                    "dangerous_pattern_found",
                    pattern=pattern,
                    path=skill_path
                )
                return False

        return True


# Singleton instance
skill_autogenerator = SkillAutogenerator()
