#!/usr/bin/env python3
"""
Synchronous MCP Skill Generation Test

This script waits for generation to complete and checks the result.
"""
import asyncio
import sys
sys.path.insert(0, '/app')

from mcp_skill_generator import mcp_skill_generator
from logging_config import get_logger

logger = get_logger(__name__)


async def test_generation():
    """Test skill generation with waiting"""
    print("\n=== Synchronous Skill Generation Test ===")

    missing_caps = ["stock_analysis", "market_data"]
    requirements = {
        "input_type": "text",
        "output_type": "report",
        "artifacts": ["FILE", "REPORT"]
    }
    goal_context = {
        "title": "Analyze AAPL stock",
        "description": "Get stock data and generate analysis report"
    }

    try:
        print(f"\nGenerating skill for: {missing_caps}")

        # This will wait for generation to complete
        plugin_id = await mcp_skill_generator.generate_skill(
            missing_capabilities=missing_caps,
            requirements=requirements,
            goal_context=goal_context
        )

        print(f"\n✓ Skill generated successfully!")
        print(f"  Plugin ID: {plugin_id}")

        # Get the plugin
        plugin = await mcp_skill_generator.get_plugin(plugin_id)

        if plugin:
            print(f"\n✓ Plugin registered in MCP:")
            print(f"  ID: {plugin.plugin_id}")
            print(f"  Version: {plugin.version}")
            print(f"  Status: {plugin.status}")
            print(f"  Capabilities: {plugin.capabilities}")

        # Check database
        from sqlalchemy import select
        from autogenerated_skill_models import AutogeneratedSkill
        from database import AsyncSessionLocal

        async with AsyncSessionLocal() as session:
            stmt = select(AutogeneratedSkill).where(
                AutogeneratedSkill.skill_id == plugin_id
            )
            result = await session.execute(stmt)
            db_skill = result.scalar_one_or_none()

            if db_skill:
                print(f"\n✓ Skill saved to database:")
                print(f"  ID: {db_skill.skill_id}")
                print(f"  Version: {db_skill.version}")
                print(f"  Status: {db_skill.status}")
                print(f"  Validation: {db_skill.validation_status}")
                if db_skill.validation_errors:
                    print(f"  Errors: {db_skill.validation_errors}")

        # Check file
        plugin_path = mcp_skill_generator.plugins_dir / f"{plugin_id}.py"
        if plugin_path.exists():
            print(f"\n✓ Plugin file created: {plugin_path}")
            with open(plugin_path, 'r') as f:
                code = f.read()
                lines = code.count('\n')
                print(f"  Lines of code: {lines}")

        return True

    except Exception as e:
        print(f"\n✗ Generation failed: {e}")
        import traceback
        traceback.print_exc()
        return False


async def main():
    result = await test_generation()
    print("\n" + "=" * 60)
    if result:
        print("✓ MCP SKILL AUTOGENERATION TEST PASSED")
    else:
        print("✗ MCP SKILL AUTOGENERATION TEST FAILED")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
