"""
MCP Auto-generated Skill: test_skill
Generated by AI-OS MCP Skill System
"""
from canonical_skills.base import Skill, SkillResult, Artifact


class MCPCapabilityTest_SkillSkill(Skill):
    """Auto-generated skill for test_skill capability."""
    
    id = "mcp.test_skill"
    version = "0.1.0"
    description = "MCP auto-generated skill for test_skill"
    
    capabilities = ["test_skill"]
    requirements = []
    
    input_schema = {
        "type": "object",
        "properties": {
            "data": {"type": "string", "description": "Input data"}
        },
        "required": ["data"]
    }
    
    output_schema = {
        "type": "object",
        "properties": {
            "result": {"type": "string"}
        }
    }
    
    produces_artifacts = ["KNOWLEDGE"]
    
    def execute(self, input_data: dict, context: dict) -> SkillResult:
        data = input_data.get("data", "")
        
        result_text = f"MCP processed: {data[:100]} with test_skill"
        
        artifact = self._artifact(
            type_="KNOWLEDGE",
            content=result_text,
            metadata={"source": "MCPCapabilityTest_SkillSkill", "capability": "test_skill"}
        )
        
        return self._success_result({"result": result_text}, [artifact])
    
    def verify(self, result: SkillResult) -> bool:
        return result.success and len(result.artifacts) > 0
