"""
MCP Auto-generated Skill: test_capability
Generated by AI-OS MCP Skill System
"""
from canonical_skills.base import Skill, SkillResult, Artifact


class MCPCapabilityTest_CapabilitySkill(Skill):
    """Auto-generated skill for test_capability capability."""
    
    id = "mcp.test_capability"
    version = "0.1.0"
    description = "MCP auto-generated skill for test_capability"
    
    capabilities = ["test_capability"]
    requirements = []
    
    input_schema = {
        "type": "object",
        "properties": {
            "data": {"type": "string", "description": "Input data"}
        },
        "required": ["data"]
    }
    
    output_schema = {
        "type": "object",
        "properties": {
            "result": {"type": "string"}
        }
    }
    
    produces_artifacts = ["KNOWLEDGE"]
    
    def execute(self, input_data: dict, context: dict) -> SkillResult:
        data = input_data.get("data", "")
        
        result_text = f"MCP processed: {data[:100]} with test_capability"
        
        artifact = self._artifact(
            type_="KNOWLEDGE",
            content=result_text,
            metadata={"source": "MCPCapabilityTest_CapabilitySkill", "capability": "test_capability"}
        )
        
        return self._success_result({"result": result_text}, [artifact])
