"""
MCP Auto-generated Skill: search
Generated by AI-OS MCP Skill System
"""
from canonical_skills.base import Skill, SkillResult, Artifact


class MCPCapabilitySearchSkill(Skill):
    """Auto-generated skill for search capability."""
    
    id = "mcp.search"
    version = "0.1.0"
    description = "MCP auto-generated skill for search"
    
    capabilities = ["search"]
    requirements = []
    
    input_schema = {
        "type": "object",
        "properties": {
            "data": {"type": "string", "description": "Input data"}
        },
        "required": ["data"]
    }
    
    output_schema = {
        "type": "object",
        "properties": {
            "result": {"type": "string"}
        }
    }
    
    produces_artifacts = ["KNOWLEDGE"]
    
    def execute(self, input_data: dict, context: dict) -> SkillResult:
        data = input_data.get("data", "")
        
        result_text = f"MCP processed: {data[:100]} with search"
        
        artifact = self._artifact(
            type_="KNOWLEDGE",
            content=result_text,
            metadata={"source": "MCPCapabilitySearchSkill", "capability": "search"}
        )
        
        return self._success_result({"result": result_text}, [artifact])
