import { useState, useEffect } from 'react';
import { apiClient } from '../api/client';

interface MCPStats {
  connected: boolean;
  active_plugins: number;
  active_generations: number;
  max_plugins: number;
  max_concurrent: number;
  cooldown_seconds: number;
}

interface DatabaseStats {
  total_skills: number;
  by_status: {
    experimental: number;
    failed: number;
    stable: number;
    deprecated: number;
  };
}

interface MCPConfig {
  pruning_threshold_days: number;
  min_success_rate: number;
}

interface MCPStatus {
  status: string;
  mcp: MCPStats;
  database: DatabaseStats;
  config: MCPConfig;
}

interface Plugin {
  plugin_id: string;
  status: string;
  capabilities: string[];
  version: string;
  execution_count: number;
  success_count: number;
  success_rate: number;
  created_at: string;
}

export default function MCPPage() {
  const [status, setStatus] = useState<MCPStatus | null>(null);
  const [plugins, setPlugins] = useState<Plugin[]>([]);
  const [filter, setFilter] = useState<string>('all');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchStatus = async () => {
    try {
      const data = await apiClient.get<MCPStatus>('/mcp/status');
      setStatus(data);
    } catch (err) {
      setError('Failed to fetch MCP status');
      console.error(err);
    }
  };

  const fetchPlugins = async () => {
    try {
      const statusFilter = filter === 'all' ? '' : filter;
      const data = await apiClient.get<{ plugins: Plugin[] }>(`/mcp/plugins?status_filter=${statusFilter}`);
      setPlugins(data.plugins || []);
    } catch (err) {
      console.error('Failed to fetch plugins:', err);
    }
  };

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      await Promise.all([fetchStatus(), fetchPlugins()]);
      setLoading(false);
    };
    loadData();

    // Auto-refresh every 5 seconds
    const interval = setInterval(() => {
      fetchStatus();
      fetchPlugins();
    }, 5000);

    return () => clearInterval(interval);
  }, [filter]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-xl">Loading MCP status...</div>
      </div>
    );
  }

  if (error && !status) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-red-500 text-xl">{error}</div>
      </div>
    );
  }

  const getStatusColor = (s: string) => {
    switch (s) {
      case 'experimental': return 'bg-yellow-500';
      case 'stable': return 'bg-green-500';
      case 'deprecated': return 'bg-gray-500';
      case 'failed': return 'bg-red-500';
      default: return 'bg-blue-500';
    }
  };

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-3xl font-bold mb-2">MCP Skill Autogeneration</h1>
        <p className="text-gray-600">Monitor and manage autogenerated skills</p>
      </div>

      {status && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <div className="bg-white rounded-lg shadow p-4">
            <div className="text-sm text-gray-600">Active Plugins</div>
            <div className="text-2xl font-bold">{status.mcp.active_plugins}</div>
            <div className="text-xs text-gray-500">max: {status.mcp.max_plugins}</div>
          </div>

          <div className="bg-white rounded-lg shadow p-4">
            <div className="text-sm text-gray-600">Active Generations</div>
            <div className="text-2xl font-bold">{status.mcp.active_generations}</div>
            <div className="text-xs text-gray-500">max: {status.mcp.max_concurrent}</div>
          </div>

          <div className="bg-white rounded-lg shadow p-4">
            <div className="text-sm text-gray-600">Total Skills</div>
            <div className="text-2xl font-bold">{status.database.total_skills}</div>
            <div className="text-xs text-gray-500">
              {status.database.by_status.experimental} experimental
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-4">
            <div className="text-sm text-gray-600">Cooldown</div>
            <div className="text-2xl font-bold">{status.mcp.cooldown_seconds}s</div>
            <div className="text-xs text-gray-500">between generations</div>
          </div>
        </div>
      )}

      <div className="mb-6">
        <div className="flex gap-2 mb-4">
          <button
            onClick={() => setFilter('all')}
            className={`px-4 py-2 rounded ${filter === 'all' ? 'bg-blue-500 text-white' : 'bg-gray-200'}`}
          >
            All
          </button>
          <button
            onClick={() => setFilter('experimental')}
            className={`px-4 py-2 rounded ${filter === 'experimental' ? 'bg-yellow-500 text-white' : 'bg-gray-200'}`}
          >
            Experimental
          </button>
          <button
            onClick={() => setFilter('stable')}
            className={`px-4 py-2 rounded ${filter === 'stable' ? 'bg-green-500 text-white' : 'bg-gray-200'}`}
          >
            Stable
          </button>
          <button
            onClick={() => setFilter('failed')}
            className={`px-4 py-2 rounded ${filter === 'failed' ? 'bg-red-500 text-white' : 'bg-gray-200'}`}
          >
            Failed
          </button>
          <button
            onClick={() => setFilter('deprecated')}
            className={`px-4 py-2 rounded ${filter === 'deprecated' ? 'bg-gray-500 text-white' : 'bg-gray-200'}`}
          >
            Deprecated
          </button>
        </div>

        <div className="bg-white rounded-lg shadow overflow-hidden">
          <table className="min-w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Plugin ID
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Status
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Capabilities
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Executions
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Success Rate
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {plugins.map((plugin) => (
                <tr key={plugin.plugin_id}>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-gray-900">{plugin.plugin_id}</div>
                    <div className="text-sm text-gray-500">{plugin.version}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full text-white ${getStatusColor(plugin.status)}`}>
                      {plugin.status}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="text-sm text-gray-900">
                      {plugin.capabilities.slice(0, 3).map(cap => (
                        <span key={cap} className="inline-block bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded mr-1 mb-1">
                          {cap}
                        </span>
                      ))}
                      {plugin.capabilities.length > 3 && (
                        <span className="text-xs text-gray-500">+{plugin.capabilities.length - 3} more</span>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {plugin.execution_count}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">
                      {plugin.success_rate !== null ? `${(plugin.success_rate * 100).toFixed(1)}%` : 'N/A'}
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div
                        className="bg-green-500 h-2 rounded-full"
                        style={{ width: `${plugin.success_rate !== null ? plugin.success_rate * 100 : 0}%` }}
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {plugins.length === 0 && (
            <div className="text-center py-12">
              <div className="text-gray-500">No plugins found</div>
            </div>
          )}
        </div>
      </div>

      {status && (
        <div className="bg-white rounded-lg shadow p-4">
          <h3 className="text-lg font-semibold mb-2">Configuration</h3>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-gray-600">Pruning Threshold:</span> {status.config.pruning_threshold_days} days
            </div>
            <div>
              <span className="text-gray-600">Min Success Rate:</span> {(status.config.min_success_rate * 100).toFixed(0)}%
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
